global using Api.Data;
global using Api.Data.Dtos;
global using Api.Data.Entities;
global using Api.Services;
global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Memory;
global using Moq;
